// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UNRI.Models.Connection;

#nullable disable

namespace UNRI.Migrations
{
    [DbContext(typeof(UNRIcontext))]
    [Migration("20221018102106_dbUNRI")]
    partial class dbUNRI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UNRI.Models.fakultas.data_fakultas", b =>
                {
                    b.Property<string>("id_fakultas")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("nm_fakultas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_fakultas");

                    b.ToTable("data_fakultas");
                });

            modelBuilder.Entity("UNRI.Models.jabatan.data_jabatan", b =>
                {
                    b.Property<int>("id_jabatan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_jabatan"), 1L, 1);

                    b.Property<string>("nm_jabatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_jabatan");

                    b.ToTable("data_jabatan");
                });

            modelBuilder.Entity("UNRI.Models.jurusan.data_jurusan", b =>
                {
                    b.Property<string>("id_jurusan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("id_fakultas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nm_jurusan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_jurusan");

                    b.ToTable("data_jurusan");
                });

            modelBuilder.Entity("UNRI.Models.pegawai.data_pegawai", b =>
                {
                    b.Property<string>("id_pegawai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("alamat_kantor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_jabatan")
                        .HasColumnType("int");

                    b.Property<string>("keterangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nm_pegawai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telp_kantor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_pegawai");

                    b.ToTable("data_pegawai");
                });

            modelBuilder.Entity("UNRI.Models.pengguna.data_pengguna", b =>
                {
                    b.Property<string>("email_pengguna")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("alamat_pengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kelamin_pengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nama_pengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password_pengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telp_pengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("email_pengguna");

                    b.ToTable("data_pengguna");
                });

            modelBuilder.Entity("UNRI.Models.prodi.data_prodi", b =>
                {
                    b.Property<string>("id_prodi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("id_jurusan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jenjang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nm_prodi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_prodi");

                    b.ToTable("data_prodi");
                });

            modelBuilder.Entity("UNRI.Models.wilayah_kerja.data_unit_kerja", b =>
                {
                    b.Property<int>("id_unit_kerja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_unit_kerja"), 1L, 1);

                    b.Property<string>("nm_unit_kerja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_unit_kerja");

                    b.ToTable("data_unit_kerja");
                });
#pragma warning restore 612, 618
        }
    }
}
